// <auto-generated />
namespace Movy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddActs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddActs));
        
        string IMigrationMetadata.Id
        {
            get { return "201706122341177_AddActs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
